symfony/src/Entity/News.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use DateTime;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class News
{
    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ManyToMany(targetEntity="Category", mappedBy="news", cascade={"persist"})
     * @JoinTable(name="news_has_categories")
     */

    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="news")
     */

    private $comments;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="news", fileNameProperty="imageName", size="imageSize")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */

    private $imageSize;

    /**
     * @param File|UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNewsId($this->getId());
        }

        return $this;
    }

    public function addCategory(Category $category)
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category)
    {
//        @TODO implement
    }

    /**
     * @return ArrayCollection|Category[]
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @var DateTime $created
     *
     * @ORM\Column(type="datetime", nullable=false)
     */
    protected $createdAt;

    public function getCreatedAt(): ?DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function updatedTimestamps(): void
    {
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new DateTime('now'));
        }
    }
}

symfony/src/Form/NewsType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\News;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class NewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('short_description')
            ->add('content')
            ->add('categories', EntityType::class, [
                'choice_label' => 'title',
                'multiple'     => true,
                'by_reference' => false,
                'class'        => Category::class,
            ])
            ->add('imageFile', VichImageType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => News::class,
        ]);
    }
}

symfony/src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Form\NewsType;
use App\Repository\NewsRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Vich\UploaderBundle\VichUploaderBundle;

/**
 * @Route("admin/news")
 */
class NewsController extends AbstractController
{
    /**
     * @Route("/", name="news_index", methods={"GET"})
     */
    public function index(
        NewsRepository $newsRepository,
        Request $request,
        PaginatorInterface $paginator
    ): Response {
        $pagination = $paginator->paginate(
            $newsRepository->findAll(),
            $request->query->getInt('page', 1),
            30
        );

        return $this->render('news/index.html.twig', [
            'news' => $pagination,
        ]);
    }


    /**
     * @Route("/new", name="news_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $news = new News();
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($news);
            $entityManager->flush();

            return $this->redirectToRoute('news_index');
        }

        return $this->render('news/new.html.twig', [
            'news' => $news,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="news_show", methods={"GET"})
     */
    public function show(News $news): Response
    {
        dump($news->getComments());

        return $this->render('news/show.html.twig', [
            'news' => $news,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="news_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, News $news): Response
    {
        $form = $this->createForm(NewsType::class, $news);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('news_index');
        }

        return $this->render('news/edit.html.twig', [
            'news' => $news,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="news_delete", methods={"DELETE"})
     */
    public function delete(Request $request, News $news): Response
    {
        if ($this->isCsrfTokenValid('delete'.$news->getId(),
            $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($news);
            $entityManager->flush();
        }

        return $this->redirectToRoute('news_index');
    }
}

symfony/templates/news/_delete_form.html.twig
<form method="post" action="{{ path('news_delete', {'id': news.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ news.id) }}">
    <button class="btn">Delete</button>
</form>

symfony/templates/news/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

<h3>Tag1s</h3>
<ul class="tags">
    {# iterate over each existing tag and render its only field: name #}
    {% dump form.categories %}
    {% for tag in form.categories %}
        {% dump tag.title %}

        <li>{{ form_row(tag.title) }}</li>
    {% endfor %}
</ul>

<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}




{#{% dump form %}#}
{#  {% for tag in form.categories %}#}
{#        <li>{{ form_row(tag.title) }}</li>#}
{#{% endfor %}#}

symfony/templates/news/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit News{% endblock %}

{% block body %}
    <h1>Edit News</h1>

    {{ include('news/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('news_index') }}">back to list</a>

    {{ include('news/_delete_form.html.twig') }}
{% endblock %}

symfony/templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}News index{% endblock %}

{% block body %}
    <h1>News index</h1>
    <div>
        <a class="btn btn-info pull-right" href="{{ path('news_new') }}">Create new</a>
    </div>

    <div class="d-flex justify-content-center">
        <div class="navigation text-center">
            {{ knp_pagination_render(news) }}
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Short description</th>
            <th>Content</th>
            <th>Category</th>
            <th>Picture</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for news in news %}

            <tr>
                <td>{{ news.id }}</td>
                <td>{{ news.title }}</td>
                <td>{{ news.shortDescription|slice(0, 100) }}</td>
                <td>{{ news.content|slice(0, 250) }}</td>
                <td>
                    {% for category in news.Categories %}
                        {{ category.title }}
                    {% endfor %}
                </td>
                <td>
                    <img class="img-thumbnail card-img-top img-fluid" src="{{ vich_uploader_asset(news, 'imageFile') }}"
                         style=""/>
                </td>
                <td>
                    <a href="{{ path('news_show', {'id': news.id}) }}">show</a>
                    <a href="{{ path('news_edit', {'id': news.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

symfony/templates/news/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New News{% endblock %}

{% block body %}
    <h1>Create new News</h1>

    {{ include('news/_form.html.twig') }}

    <a href="{{ path('news_index') }}">back to list</a>
{% endblock %}

symfony/templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block body %}
    {% dump news %}
    <h1>News</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ news.id }}</td>
        </tr>
        <tr>
            <th>Short_description</th>
            <td>{{ news.shortDescription }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ news.content }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>
                {% for comment in news.Categories %}
                    <span>
                            {{ comment.title }}
                        </span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Picture</th>
            <td>
                <img src="{{ vich_uploader_asset(news, 'imageFile') }}" style=""/>
            </td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('news_index') }}">back to list</a>

    <a href="{{ path('news_edit', {'id': news.id}) }}">edit</a>

    {{ include('news/_delete_form.html.twig') }}

{% endblock %}

symfony/templates/news/show_public.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{% block body %}
    <h1>News</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ news.id }}</td>
        </tr>
        <tr>
            <th>Short_description</th>
            <td>{{ news.shortDescription }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ news.content }}</td>
        </tr>
        <tr>
            <th>Comment</th>
            <td>
                {% for tag in news.comments %}
                    <span>
                            {{ tag.content }}
                        {{ tag.owner }}
                        </span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Picture</th>
            <td>{{ news.picture }}</td>
        </tr>
        </tbody>
    </table>

{% endblock %}